version: '3'
services:
  front:
    build:
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: frontend
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    depends_on:
      - backend
  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: backend
    networks:
      - mern-stack-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-stack-network
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mlnthapa
      - MONGO_INITDB_ROOT_PASSWORD=LA1XsG3BlvJ85cWx
      - MONGO_INITDB_DATABASE=milan
networks:
  mern-stack-network:
volumes:
  mongoData: